---
title: "GPM Performance Report(Wind)"
author: "Xuran ZENG"
date: "2020/12/8"
output: 
  html_document: 
    toc: yes
    toc_float: true 
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=TRUE, warning=FALSE, message=FALSE)
```

```{r echo=FALSE}
library(xts)
library(PerformanceAnalytics)
library(lubridate)
library(quantmod)
library(TTR)
library(ggplot2)
library(grid)
library(gridExtra)
library(corrplot)
library(tidyr)
library(knitr)

source("d:\\Users\\XuranZENG\\Desktop\\asset_allocation\\cal_ret.R")
source("d:\\Users\\XuranZENG\\Desktop\\asset_allocation\\models.R")


```

```{r results="hide"}
library(WindR)
w.start()
begintime<-"2013-07-29"  
endtime<-Sys.time()

Risky<-c("H00909.CSI",  #沪深300材料
         "H00910.CSI",  #沪深300工业
         "H00911.CSI",  #沪深300可选
         "H00912.CSI",  #沪深300消费
         "H00913.CSI",  #沪深300医药
         "H00914.CSI",  #沪深300金融
         "H00915.CSI",  #沪深300信息
         "H00300.CSI",  #沪深300
         "H00905.CSI",  #中证500
         "399606.SZ",   #创业板
         "H00140.SH",   #国债指数
         "518800.SH"    #黄金ETF
         )   
cp<-c("N11077.SH",      #十年国债
      "N00140.SH"       #五年国债
      )  


```

```{r echo=FALSE}
symbols<-c(Risky,cp)

wdata<-as.data.frame(w.wsd(symbols,'close',begintime,endtime))


rownames(wdata)<-as.Date(wdata[,'Data.DATETIME'])


wdata<-subset(wdata,select=-c(ErrorCode,Field,Data.DATETIME))

colnames(wdata)<-symbols

returns_data<-na.omit(ROC(wdata)) 

```


```{r echo=FALSE}
colnames(returns_data)<-symbols
returns_data<-as.xts(returns_data)
```

```{r}
N<-3 #number of assets chosen
P<-12 #periods to calculate momentum
weights_data<-GPM(wdata,N,P)
```

```{r echo=FALSE}
weights_data<-xts(weights_data[,-1],ymd(weights_data[,1])) ## convert to xts

colnames(weights_data)<-c("材料","工业","可选","消费","医药","金融","信息","沪深300","中证500","创业板","国债指数","黄金ETF","十年国债","五年国债")

colnames(returns_data)<-c("材料","工业","可选","消费","医药","金融","信息","沪深300","中证500","创业板","国债指数","黄金ETF","十年国债","五年国债")

benchmark.ret<-cbind(returns_data$沪深300, returns_data$国债指数)
benchmark.portf<-portf.sixty_fourty(benchmark.ret, rebalance_on="months", verbose=T)

bench.ret<-benchmark.portf$returns
colnames(bench.ret)<-"Benchmark"

hs300.ret<-returns_data$沪深300
colnames(hs300.ret)<-"hs300"

portf <- Return.portfolio(returns_data, weights = weights_data, verbose=T)

portf.ret<-portf$returns


colnames(portf.ret)<-"Strategy"
```

```{r echo=FALSE}
ret<-cbind(portf.ret, bench.ret)

colnames<-c("Strategy","Benchmark")
```

## 一、业绩总览
```{r echo=FALSE}

five_years<-'2015-01-01/2020-01-01'

ret.five_years<-ret[five_years,]



```

```{r echo=FALSE}
charts.PerformanceSummary(ret.five_years, date.format="%Y%m")
```

```{r echo=FALSE}
tab.perf2(portf.ret[five_years,],bench.ret[five_years,])


```

## 二、持仓比例
```{r echo=FALSE}
chart.StackedBar(portf$BOP.Value[five_years], date.format="%y/%m", colorset=rainbow12equal, border=NA)
```

## 三、收益统计
### 月度回报


```{r echo=FALSE}

cal_ret.portf<-apply.monthly(portf.ret[five_years,],Return.cumulative)
cal_ret.bench<-apply.monthly(bench.ret[five_years,],Return.cumulative)
cal_ret<-cbind(cal_ret.portf,cal_ret.bench)
cal_ret<-round(cal_ret,2)
cal_ret<-cbind(date=as.Date(rownames(as.data.frame(cal_ret))),as.data.frame(cal_ret))
#cal_ret
cal_ret <- gather(data = cal_ret, key = "type", value = "return", Strategy, Benchmark)

ggplot(data = cal_ret,aes(x = date,y = return,fill = type))+
  scale_x_date(date_breaks="6 months",date_labels="%D")+
  geom_col(position = 'dodge')
```

```{r echo=FALSE}

cal_annual_ret.portf<-calendar_ret(portf.ret[five_years,])
kable(cal_annual_ret.portf)

cal_annual_ret.bench<-calendar_ret(bench.ret[five_years,])
kable(cal_annual_ret.bench)


#grid.newpage()
#grid.table(cal_annual_ret.portf)

#grid.newpage()
#grid.table(cal_annual_ret.bench)

```

### 区间回报
```{r echo=FALSE}
ret_1_week<-Return.cumulative(ret[paste((as.Date(as.Date(Sys.time())) - dweeks(1)),as.Date(Sys.time()) ,sep = "/"),])
#rownames(ret_1_week)<-'近一周'

ret_1_month<-Return.cumulative(ret[paste((as.Date(as.Date(Sys.time())) - dmonths(1)),as.Date(Sys.time()) ,sep = "/"),])
#rownames(ret_1_month)<-'近一月'

ret_3_months<-Return.cumulative(ret[paste((as.Date(as.Date(Sys.time())) - dmonths(3)),as.Date(Sys.time()) ,sep = "/"),])
#rownames(ret_3_months)<-'近三月'

ret_6_months<-Return.cumulative(ret[paste((as.Date(as.Date(Sys.time())) - dmonths(6)),as.Date(Sys.time()) ,sep = "/"),])
#rownames(ret_6_months)<-'近六月'

ret_ytd<-Return.cumulative(ret[paste(paste(year(Sys.time()),"01","01",sep = "-"),as.Date(Sys.time()) ,sep = "/"),])
#rownames(ret_ytd)<-'年初至今'

ret_1_year<-Return.cumulative(ret[paste((as.Date(as.Date(Sys.time())) - dyears(1)),as.Date(Sys.time()) ,sep = "/"),])
#rownames(ret_1_year)<-'近一年'

ret_3_year<-Return.cumulative(ret[paste((as.Date(as.Date(Sys.time())) - dyears(3)),as.Date(Sys.time()) ,sep = "/"),])
#rownames(ret_3_year)<-'近三年'

ret_5_year<-Return.cumulative(ret[paste((as.Date(as.Date(Sys.time())) - dyears(5)),as.Date(Sys.time()) ,sep = "/"),])
#rownames(ret_5_year)<-'近五年'

ret_periods<-rbind(ret_1_week,ret_1_month,ret_3_months,ret_6_months,ret_ytd,ret_1_year,ret_3_year,ret_5_year)
ret_periods<-round(ret_periods,2)
#rownames(ret_periods)<-1:8
rownames(ret_periods)<-c("近一周","近一月","近三月","近六月","年初至今","近一年","近三年","近五年")


ret_periods<-as.data.frame(cbind(date=rownames(ret_periods),ret_periods))
ret_periods <- gather(data =ret_periods, key = "type", value = "return", Strategy, Benchmark)

ret_periods$date <- factor(ret_periods$date,levels=c("近一周","近一月","近三月","近六月","年初至今","近一年","近三年","近五年"))

ggplot(data = ret_periods,aes(x = date,y = return,fill = type))+
  geom_col(position = 'dodge')

```

```{r echo=FALSE}
ret_periods<-rbind(ret_1_week,ret_1_month,ret_3_months,ret_6_months,ret_ytd,ret_1_year,ret_3_year,ret_5_year)
ret_periods<-round(ret_periods,2)
#rownames(ret_periods)<-1:8
rownames(ret_periods)<-c("近一周","近一月","近三月","近六月","年初至今","近一年","近三年","近五年")
kable(ret_periods)
```

## 四、资产相关性

```{r echo=FALSE}
cor<-cor(returns_data[five_years,])

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(cor, method="color", col=col(200),  
         type="upper", order="hclust", 
         addCoef.col = "black", #添加相关系数
         tl.col="black", tl.srt=45, #修改字体

         diag=FALSE 
         )
```
